
# This script takes as input a list of values for each locus: an effect size value and a likelihood surface discrete values of selection coefficients -> generated by simulate.R (called sc_es.txt)

# Rscript mleS.R infile.txt

args <- commandArgs(trailingOnly = TRUE);
infile <- args[1];
doplot <- as.numeric(args[2]);
rm(args);

source("ml_funcs.R");

# reading file

values_tot=read.table(infile, sep="\t", header=T, stringsAsFact=F)
niter=max(values_tot[,1]) # how many iterations

res=matrix(NA, nrow=niter, ncol=5) # true_selcoeff S sel h2 S_known sel_know h2_known

# for each iteration
for (n in 1:niter) {

	values=values_tot[which(values_tot[,1]==n),]

	h2=values$h2[1]; # hereditability, the same for all sites
	K=nrow(values); # how many loci
	esizes=values$beta_es; # per-site calculated effect size
	selcoeff=values$selcoeff; # sel coeff bin
	selcoeff_simul=values$selcoeff_simul; # sel coeff actually simulated

	# bins of sel coeff
	cats=colnames(values)[12:(ncol(values)-1)]
	cats=as.numeric(unlist(strsplit(cats, split="X")))
	cats=cats[which(!is.na(cats))] # discrete bins for the likelihood
	#cats=cats/2e4

	selcoeffs=as.matrix(values[,12:(ncol(values)-1)]) # matrix of likelihood curves for estimated selection coefficients
	# for (j in 1:nrow(selcoeffs)) selcoeffs[j,]=selcoeffs[j,]/sum(selcoeffs[j,]) # if you want to normalize them, not recommended

	# here we assume to know h2, eventually one can jointly optimized both S and h2, or simply their ratio

	# computing accuracy in re-estimating the mean of selection coefficients across all loci
	mu_true=mean(selcoeff_simul, na.rm=T)
	res[n,1]=mu_true;

	# OPTIMIZE ml function using Brent

	# first I get the best upepr bound, trying different values, as a check of sanity
	mle=c(optimize(f=ml, interval=c(0.1,20), es=esizes, sc=selcoeffs, h2=h2, denom=10, cats=cats, maximum=F)$obj,
	optimize(f=ml, interval=c(0.1,50), es=esizes, sc=selcoeffs, h2=h2, denom=10, cats=cats, maximum=F)$obj,
	optimize(f=ml, interval=c(0.1,100), es=esizes, sc=selcoeffs, h2=h2, denom=10, cats=cats, maximum=F)$obj,
	optimize(f=ml, interval=c(0.1,200), es=esizes, sc=selcoeffs, h2=h2, denom=10, cats=cats, maximum=F)$obj,
	optimize(f=ml, interval=c(0.1,400), es=esizes, sc=selcoeffs, h2=h2, denom=10, cats=cats, maximum=F)$obj,
	optimize(f=ml, interval=c(0.1,600), es=esizes, sc=selcoeffs, h2=h2, denom=10, cats=cats, maximum=F)$obj )
	ubound=c(20,50,100,200,400,600)[which.min(mle)[1]] # this [1] in case of multiple hits of min value take the first
	if (is.na(ubound)) ubound=400;
	

	# optimize the ML function and get a MLE of S
	mle_S=optimize(f=ml, interval=c(0.1,ubound), es=esizes, sc=selcoeffs, h2=h2, denom=10, cats=cats, maximum=F)$min
	# denom 10 measures the skewness of normal distribution assumed

	if (mle_S<(0.11) | mle_S>(595)) mle_S=NA; # if no convergence

	# then re-estimate the selection coefficient
	esti_selcoeff=mle_S*esizes/h2

	# draft code to estimate the ratio rather than absolute value of S [obsolete]
	#rat=optimize(f=mlr, interval=c(0.1,800), es=esizes, sc=selcoeffs, denom=10, cats=cats, maximum=F)$min
	#rat*h2
	#mle_S

	# then take the mean across all estimated selection coefficients for all loci
        mu_esti=mean(esti_selcoeff, na.rm=T)

	# record the results
	res[n,2:3]=c(mle_S, mu_esti);
	
	# draft code to estimate h2 as well [obsolete and not working]
	#mle_S=optim(par=c(100, 0.7), fn=ml2, method = c("L-BFGS-B"),lower = c(0.1,0.3), upper = c(500, 0.9), es=esizes, sc=selcoeffs, denom=10, cats=cats)
	#if (mle_S[1]<1 | mle_S[1]>495 | mle_S[2]<0.31 | mle_S[2]>0.89) mle_S=NA;
	# optimization does not work

	# as an additional analysis, compute the bias in case of KNOWN selection coefficients
	# OPTIMIZE ml in case of KNOWN selection coefficient using Brent

	true_selcoeffs=selcoeffs;
	if (min(selcoeff_simul)>0) {
		for (l in 1:nrow(selcoeffs)) true_selcoeffs[l,]=dnorm(cats, mean=selcoeff_simul[l], sd=selcoeff_simul[l]/20);
	} else {
		for (l in 1:nrow(selcoeffs)) true_selcoeffs[l,]=dnorm(cats, mean=0, sd=0.1);
	}

	mle_S=optimize(f=ml, interval=c(0.1,400), es=esizes, sc=true_selcoeffs, h2=h2, denom=10, cats=cats, maximum=F)$min
	if (mle_S<0.11 | mle_S>395) mle_S=NA;
	esti_selcoeff=mle_S*esizes/h2

        mu_esti=mean(esti_selcoeff, na.rm=T)
	res[n,4:5]=c(mle_S, mu_esti);

}

# print detailed results for each locus, for debug
if (doplot) print(res)

# print: mean hat{S}, std hat{S}, std bias, rmsd, std bias using median, rmsd using median, + the same assuming known sel coeffs

out=c(
mean(res[,2], na.rm=T), sd(res[,2], na.rm=T), mean((res[,3]-res[,1])/res[,1],na.rm=T), sqrt(mean( (res[,3]-res[,1])^2, na.rm=T)), median((res[,3]-res[,1])/res[,1],na.rm=T), sqrt(median( (res[,3]-res[,1])^2, na.rm=T)), 
mean(res[,4], na.rm=T), sd(res[,4], na.rm=T), mean((res[,5]-res[,1])/res[,1],na.rm=T), sqrt(mean( (res[,5]-res[,1])^2, na.rm=T)), median((res[,5]-res[,1])/res[,1],na.rm=T), sqrt(median( (res[,5]-res[,1])^2, na.rm=T))  )

cat(out, sep="\t")
cat("\t");

# print as stdout


